version: '3.8'

services:
  mysql:
    container_name: mysql-sql-intec
    image: mysql:8.0
    environment:
      MYSQL_USER: hanagami
      MYSQL_PASSWORD: maxime
      MYSQL_DATABASE: gamesocial_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-intec
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  gsn-api:
    container_name: gsn-api
    image: gsn/gsn:1.0.0
    ports:
      - "8088:8088"
    networks:
      - spring-demo
    depends_on:
      - mysql
networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
